apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-canary
  labels:
    app: api
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      track: canary
  template:
    metadata:
      labels:
        app: api
        track: canary
    spec:
      containers:
        - name: api
          image: nginx:1.27
          ports:
            - containerPort: 80
