events { worker_connections 1024; }
http {
    server {
        listen 8080;
        root /ruta/abs/a/web;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location /admin {
            auth_basic "Area restringida";
            auth_basic_user_file /ruta/abs/auth/.htpasswd;
            return 200 "admin area\n";
            default_type text/plain;
        }
    }
}
