apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-green
  labels:
    app: api
    slot: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
      slot: green
  template:
    metadata:
      labels:
        app: api
        slot: green
    spec:
      containers:
        - name: api
          image: nginx:1.27
          ports:
            - containerPort: 80
