events { worker_connections 1024; }
http {
    server {
        listen 8080;
        # TODO: root, index index.php index.html
        location / {
            # TODO: try_files $uri $uri/ /index.php?$query_string;
        }
        # TODO: location ~ \.php$ con fastcgi_pass, include fastcgi_params,
        #       fastcgi_param SCRIPT_FILENAME
    }
}
