# 03-db/pv-pvc.yaml — PersistentVolume y PersistentVolumeClaim para PostgreSQL
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: tienda
    component: db
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/postgres
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: tienda-online
  labels:
    app: tienda
    component: db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: postgres-pv
  resources:
    requests:
      storage: 5Gi
