# 03-db/service.yaml — Headless Service (necesario para el StatefulSet de postgres)
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: tienda-online
  labels:
    app: tienda
    component: db
spec:
  clusterIP: None
  selector:
    app: tienda
    component: db
  ports:
    - port: 5432
      targetPort: postgres
      name: postgres
