# nginx.conf del ejercicio (para editar)
# TODO: completa este archivo según el enunciado del README.md
events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;
        # TODO: añade location / con root apuntando a la carpeta web/
        # e index index.html
    }
}
