events { worker_connections 1024; }
http {
    # TODO: activar gzip con gzip_types, gzip_min_length, gzip_comp_level, gzip_vary
    server {
        listen 8080;
        # TODO: root e index
        location / { try_files $uri $uri/ =404; }
    }
}
