events { worker_connections 1024; }
http {
    server {
        listen 8080;
        root /ruta/abs/a/web;
        index index.html;

        location = /old {
            return 301 /new;
        }

        location = /new {
            default_type text/plain;
            return 200 "nueva ruta\n";
        }

        location /v1/ {
            rewrite ^/v1/(.*)$ /$1 break;
            try_files $uri $uri/ =404;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
