-- Consulta 08: NÚMERO DE PAGOS Y TOTAL COBRADO POR MÉTODO
--
-- Objetivo: resumir la tabla de pagos agrupando por método de pago.
--
-- Debe devolver:
--   metodo        → pg.metodo
--   num_pagos     → COUNT(*) de pagos
--   total_cobrado → SUM(pg.monto) redondeado a 2 decimales
--
-- Ordena por total_cobrado descendente y, en caso de empate, por metodo.
-- TODO: escribe aquí tu consulta
