-- Consulta 03: TOP 3 PRODUCTOS MÁS VENDIDOS
--
-- Objetivo: identificar los 3 productos con más unidades vendidas,
-- ignorando los pedidos cancelados. Usa una ventana ROW_NUMBER() para
-- ordenar (desempate alfabético por nombre).
--
-- Debe devolver:
--   nombre    → nombre del producto
--   unidades  → unidades totales vendidas
--
-- Solo las 3 primeras posiciones, en el orden del ranking.
-- TODO: escribe aquí tu consulta
