-- Consulta 09: COMPARATIVA MENSUAL DE INGRESOS
--
-- Objetivo: con una CTE que agrupa los ingresos por mes (pedidos
-- válidos), usar LAG() para traer el valor del mes anterior y calcular
-- la variación porcentual respecto a ese mes.
--
-- Debe devolver:
--   mes             → 'YYYY-MM'
--   ingresos        → SUM redondeado a 2 decimales
--   mes_anterior    → ingresos del mes anterior (NULL en el primero)
--   variacion_pct   → porcentaje de variación redondeado a 2 decimales
--
-- Ordena por mes ascendente.
-- TODO: escribe aquí tu consulta
