-- Consulta 10: CLIENTES CON SALDO PENDIENTE
--
-- Objetivo: para cada cliente, restar a la suma de sus pedidos NO
-- cancelados el total que ha pagado (suma de pagos de sus pedidos,
-- obtenida con una subconsulta y LEFT JOIN). Solo mostrar los clientes
-- con saldo pendiente > 0 (usa HAVING).
--
-- Debe devolver:
--   cliente        → c.nombre
--   total_pedidos  → suma de pedidos no cancelados (2 decimales)
--   total_pagado   → suma de pagos (2 decimales)
--   saldo_pendiente→ diferencia (2 decimales)
--
-- Ordena por saldo_pendiente descendente.
-- TODO: escribe aquí tu consulta
