-- Consulta 04: TICKET MEDIO POR CLIENTE vs MEDIA GLOBAL
--
-- Objetivo: para cada cliente con pedidos válidos, calcular su ticket
-- medio (AVG del total) y compararlo con la media global de todos los
-- pedidos válidos, obtenida con una subconsulta escalar.
--
-- Debe devolver:
--   cliente       → c.nombre
--   ticket_medio  → AVG redondeado a 2 decimales
--   media_global  → media global redondeada a 2 decimales
--
-- Ordena por ticket_medio descendente.
-- TODO: escribe aquí tu consulta
