-- Consulta 12: STOCK ACUMULADO POR PRODUCTO
--
-- Objetivo: reconstruir la evolución del stock de cada producto
-- acumulando (SUM OVER PARTITION BY) los movimientos de inventario.
--
-- Debe devolver:
--   producto         → nombre del producto
--   fecha            → m.fecha del movimiento
--   tipo             → m.tipo
--   cantidad         → m.cantidad
--   stock_acumulado  → SUM(m.cantidad) OVER (PARTITION BY m.producto_id
--                      ORDER BY m.fecha, m.id)
--
-- Ordena por producto_id, fecha y id del movimiento.
-- TODO: escribe aquí tu consulta
