events { worker_connections 1024; }
http {
    server {
        listen 8080;
        # TODO: root e index
        location / { try_files $uri $uri/ =404; }
        # TODO: location /admin con auth_basic y auth_basic_user_file
    }
}
