events { worker_connections 1024; }
http {
    # TODO: geo $blocked { default 0; <IP> 1; }
    server {
        listen 8080;
        # TODO: root, index
        location / {
            # TODO: if ($blocked) { return 403; }
            try_files $uri $uri/ =404;
        }
        # TODO: location /admin con allow 10.0.0.0/8; deny all;
    }
}
