events { worker_connections 1024; }
http {
    # TODO: limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;
    server {
        listen 8080;
        # TODO: root, index
        # TODO: location /api/ con limit_req zone=api_limit burst=10 nodelay
        location / { try_files $uri $uri/ =404; }
    }
}
