events { worker_connections 1024; }
http {
    server {
        listen 8080 default_server;
        server_name _;
        return 444;
    }
    server {
        listen 8080;
        server_name app1.local;
        root /ruta/abs/a/web/app1;
        index index.html;
        location / { try_files $uri $uri/ =404; }
    }
    server {
        listen 8080;
        server_name app2.local;
        root /ruta/abs/a/web/app2;
        index index.html;
        location / { try_files $uri $uri/ =404; }
    }
}
