# TODO: crea tu Dockerfile
# FROM node:20-alpine
# ENV PORT=3000 NODE_ENV=production
# WORKDIR /app
# COPY app/package.json ./
# RUN npm ci --omit=dev
# COPY app/ ./
# EXPOSE 3000
# CMD ["node", "server.js"]
