name: Secrets
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Desplegar
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: ./deploy.sh
