# conf.d/03-logging.conf — Log format estructurado (JSON) con tiempos

log_format json escape=json '{'
    '"time":"$time_iso8601",'
    '"remote_addr":"$remote_addr",'
    '"request":"$request",'
    '"status":$status,'
    '"body_bytes_sent":$body_bytes_sent,'
    '"request_time":$request_time,'
    '"upstream_response_time":"$upstream_response_time",'
    '"upstream_addr":"$upstream_addr",'
    '"upstream_cache_status":"$upstream_cache_status"'
'}';

access_log /var/log/nginx/access.json json;
error_log  /var/log/nginx/error.log warn;
