events { worker_connections 1024; }
http {
    # TODO: upstream app_backend con ip_hash, server 9001 y 9002
    server {
        listen 8080;
        location / {
            # TODO: proxy_pass y proxy_set_header Host, X-Forwarded-For
        }
    }
}
