events { worker_connections 1024; }
http {
    server {
        listen 8080;
        # TODO: root e index
        location / { try_files $uri $uri/ =404; }
        # TODO: location /descargas/ con alias, autoindex on, exact_size off
    }
}
