events { worker_connections 1024; }
http {
    # TODO: upstream app_backend con server 127.0.0.1:9001
    server {
        listen 8080;
        location / {
            # TODO: proxy_pass http://app_backend;
            # TODO: proxy_set_header Host, X-Real-IP, X-Forwarded-For, X-Forwarded-Proto
        }
    }
}
