events { worker_connections 1024; }
http {
    server {
        listen 8080;
        # TODO: root e index
        # TODO: location ~* \.php$ con return 403
        # TODO: location ~* \.(jpg|png|gif|svg)$ con expires 30d
        # TODO: location ~* \.(css|js)$ con expires 1y
        location / { try_files $uri $uri/ =404; }
    }
}
