# nginx.conf del ejercicio (para editar)
events { worker_connections 1024; }
http {
    server {
        listen 8080;
        server_name localhost;
        # TODO: root, index y try_files
        location / {
            # TODO: try_files $uri $uri/ =404;
        }
    }
}
