events { worker_connections 1024; }
http {
    geo $blocked {
        default 0;
        192.168.99.50 1;
    }

    server {
        listen 8080;
        root /ruta/abs/a/web;
        index index.html;

        location / {
            if ($blocked) { return 403; }
            try_files $uri $uri/ =404;
        }

        location /admin {
            allow 10.0.0.0/8;
            deny all;
            return 200 "admin interno\n";
            default_type text/plain;
        }
    }
}
