events { worker_connections 1024; }
http {
    server {
        listen 8080;
        # TODO: root e index
        location / { try_files $uri $uri/ =404; }
        # TODO: location /api/ con proxy_pass http://127.0.0.1:9001;
    }
}
