worker_processes auto;
worker_rlimit_nofile 65535;

events {
    worker_connections 1024;
}

http {
    # TODO: sube worker_connections a 4096, multi_accept on
    # TODO: sendfile, tcp_nopush, tcp_nodelay
    # TODO: keepalive_timeout 65, keepalive_requests 1000
    # TODO: client_body_buffer_size 16k, client_max_body_size 10m
    # TODO: proxy_buffer_size 16k, proxy_buffers 8 16k

    server {
        listen 8080;
        location / {
            return 200 "tuned\n";
            default_type text/plain;
        }
    }
}
