events { worker_connections 1024; }
http {
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

    server {
        listen 8080;
        root /ruta/abs/a/web;
        index index.html;

        location /api/ {
            limit_req zone=api_limit burst=10 nodelay;
            limit_req_status 429;
            return 200 "ok\n";
            default_type text/plain;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
