events { worker_connections 1024; }
http {
    # TODO: proxy_cache_path ... keys_zone=api_cache:10m ...
    # TODO: upstream app_backend con server 127.0.0.1:9001
    server {
        listen 8080;
        location /api/ {
            # TODO: proxy_pass, proxy_cache api_cache, proxy_cache_valid 200 10m
            # TODO: proxy_cache_key, add_header X-Cache-Status
        }
    }
}
