events { worker_connections 1024; }
http {
    log_format main '$remote_addr - [$time_local] "$request" '
                    '$status $body_bytes_sent rt=$request_time '
                    'urt=$upstream_response_time';

    access_log /ruta/logs/access.log main;
    error_log  /ruta/logs/error.log warn;

    server {
        listen 8080;
        location / {
            return 200 "logged\n";
            default_type text/plain;
        }
    }
}
