events { worker_connections 1024; }
http {
    geo $blocked_country {
        default 0;
        10.0.0.0/8       0;
        192.168.99.0/24   1;
        203.0.113.0/24    1;
    }

    map $blocked_country $access_action {
        0 allow;
        1 deny;
    }

    server {
        listen 8080;
        root /ruta/abs/a/web;
        index index.html;

        location / {
            if ($access_action = deny) { return 403; }
            try_files $uri $uri/ =404;
        }
    }
}
