# TODO: crea tu Dockerfile
# FROM node:20-alpine
# WORKDIR /app
# RUN addgroup -S app && adduser -S app -G app
# COPY --chown=app:app app/package.json ./
# RUN npm ci --omit=dev
# COPY --chown=app:app app/ ./
# USER app
# EXPOSE 3000
# CMD ["node", "server.js"]
