events { worker_connections 1024; }
http {
    # TODO: log_format main con $request_time y $upstream_response_time
    # TODO: access_log ... main;
    # TODO: error_log ... warn;
    server {
        listen 8080;
        location / {
            return 200 "logged\n";
            default_type text/plain;
        }
    }
}
