# 04-backend/service.yaml — Service ClusterIP del backend
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: tienda-online
  labels:
    app: tienda
    component: backend
spec:
  type: ClusterIP
  selector:
    app: tienda
    component: backend
  ports:
    - port: 5000
      targetPort: http
      name: http
