events { worker_connections 1024; }
http {
    # TODO: include mime.types y default_type
    server {
        listen 8080;
        # TODO: root, index
        location / {
            # TODO
        }
        # TODO: location /api/ con default_type application/json
    }
}
