events { worker_connections 1024; }
http {
    server {
        listen 8080;
        # TODO: root e index
        # TODO: location ~* \.(css|js)$ con expires 1y y Cache-Control immutable
        # TODO: location ~* \.(png|jpg|svg)$ con expires 30d
        # TODO: location ~* \.html$ con Cache-Control no-cache
        location / { try_files $uri $uri/ =404; }
    }
}
