-- Consulta 06: RANKING DE CLIENTES POR GASTO TOTAL
--
-- Objetivo: ordenar a los clientes por cuánto han gastado (suma de
-- pedidos no cancelados) y asignarles un rango con RANK().
--
-- Debe devolver:
--   cliente     → c.nombre
--   gasto_total → SUM redondeado a 2 decimales
--   rango       → RANK() sobre el gasto total descendente
--
-- Ordena por rango y, en caso de empate, por nombre.
-- TODO: escribe aquí tu consulta
