# nginx.conf del ejercicio (para editar)
events { worker_connections 1024; }
http {
    # TODO: server default_server que devuelva 444
    # TODO: server app1.local -> root web/app1
    # TODO: server app2.local -> root web/app2
}
