name: Condicional
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build"
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Desplegando a producción"
