apiVersion: v1
kind: Secret
metadata:
  name: tienda-secrets
  namespace: tienda-online
  labels:
    app: tienda
    component: config
type: Opaque
stringData:
  POSTGRES_PASSWORD: "tienda-super-secreta"
  BACKEND_API_KEY: "api-key-tienda-2024"
  JWT_SECRET: "jwt-super-secreto-tienda"
